--- language_code
insert into book.language_code (code, code_name) VALUES 
('ab', 'Abkhazian'),
('aa', 'Afar'),
('af', 'Afrikaans'),
('ak', 'Akan'),
('sq', 'Albanian'),
('am', 'Amharic'),
('ar', 'Arabic'),
('an', 'Aragonese'),
('hy', 'Armenian'),
('as', 'Assamese'),
('av', 'Avaric'),
('ae', 'Avestan'),
('ay', 'Aymara'),
('az', 'Azerbaijani'),
('bm', 'Bambara'),
('ba', 'Bashkir'),
('eu', 'Basque'),
('be', 'Belarusian'),
('bn', 'Bengali (Bangla)'),
('bh', 'Bihari'),
('bi', 'Bislama'),
('bs', 'Bosnian'),
('br', 'Breton'),
('bg', 'Bulgarian'),
('my', 'Burmese'),
('ca', 'Catalan'),
('ch', 'Chamorro'),
('ce', 'Chechen'),
('ny', 'Chichewa, Chewa, Nyanja'),
('zh', 'Chinese'),
('zh-Hans', 'Chinese (Simplified)'),
('zh-Hant', 'Chinese (Traditional)'),
('cv', 'Chuvash'),
('kw', 'Cornish'),
('co', 'Corsican'),
('cr', 'Cree'),
('hr', 'Croatian'),
('cs', 'Czech'),
('da', 'Danish'),
('dv', 'Divehi'),
('dv', 'Dhivehi'),
('dv', 'Maldivian'),
('nl', 'Dutch'),
('dz', 'Dzongkha'),
('en', 'English'),
('eo', 'Esperanto'),
('et', 'Estonian'),
('ee', 'Ewe'),
('fo', 'Faroese'),
('fj', 'Fijian'),
('fi', 'Finnish'),
('fr', 'French'),
('ff', 'Fula'),
('ff', 'Fulah'),
('ff', 'Pulaar'),
('ff', 'Pular'),
('gl', 'Galician'),
('gd', 'Gaelic (Scottish)'),
('gv', 'Gaelic (Manx)'),
('ka', 'Georgian'),
('de', 'German'),
('el', 'Greek'),
('gn', 'Guarani'),
('gu', 'Gujarati'),
('ht', 'Haitian Creole'),
('ha', 'Hausa'),
('he', 'Hebrew'),
('hz', 'Herero'),
('hi', 'Hindi'),
('ho', 'Hiri Motu'),
('hu', 'Hungarian'),
('is', 'Icelandic'),
('io', 'Ido'),
('ig', 'Igbo'),
('id', 'Indonesian'),
('in', 'Indonesian'),
('ia', 'Interlingua'),
('ie', 'Interlingue'),
('iu', 'Inuktitut'),
('ik', 'Inupiak'),
('ga', 'Irish'),
('it', 'Italian'),
('ja', 'Japanese'),
('jv', 'Javanese'),
('kl', 'Kalaallisut'),
('kl', 'Greenlandic'),
('kn', 'Kannada'),
('kr', 'Kanuri'),
('ks', 'Kashmiri'),
('kk', 'Kazakh'),
('km', 'Khmer'),
('ki', 'Kikuyu'),
('rw', 'Kinyarwanda (Rwanda)'),
('rn', 'Kirundi'),
('ky', 'Kyrgyz'),
('kv', 'Komi'),
('kg', 'Kongo'),
('ko', 'Korean'),
('ku', 'Kurdish'),
('kj', 'Kwanyama'),
('lo', 'Lao'),
('la', 'Latin'),
('lv', 'Latvian (Lettish)'),
('li', 'Limburgish ( Limburger)'),
('ln', 'Lingala'),
('lt', 'Lithuanian'),
('lu', 'Luga-Katanga'),
('lg', 'Luganda, Ganda'),
('lb', 'Luxembourgish'),
('gv', 'Manx'),
('mk', 'Macedonian'),
('mg', 'Malagasy'),
('ms', 'Malay'),
('ml', 'Malayalam'),
('mt', 'Maltese'),
('mi', 'Maori'),
('mr', 'Marathi'),
('mh', 'Marshallese'),
('mo', 'Moldavian'),
('mn', 'Mongolian'),
('na', 'Nauru'),
('nv', 'Navajo'),
('ng', 'Ndonga'),
('nd', 'Northern Ndebele'),
('ne', 'Nepali'),
('no', 'Norwegian'),
('nb', 'Norwegian bokmål'),
('nn', 'Norwegian nynorsk'),
('ii', 'Nuosu'),
('oc', 'Occitan'),
('oj', 'Ojibwe'),
('cu', 'Old Church Slavonic'),
('cu', 'Old Bulgarian'),
('or', 'Oriya'),
('om', 'Oromo (Afaan Oromo)'),
('os', 'Ossetian'),
('pi', 'Pāli'),
('ps', 'Pashto, Pushto'),
('fa', 'Persian (Farsi)'),
('pl', 'Polish'),
('pt', 'Portuguese'),
('pa', 'Punjabi (Eastern)'),
('qu', 'Quechua'),
('rm', 'Romansh'),
('ro', 'Romanian'),
('ru', 'Russian'),
('se', 'Sami'),
('sm', 'Samoan'),
('sg', 'Sango'),
('sa', 'Sanskrit'),
('sr', 'Serbian'),
('sh', 'Serbo-Croatian'),
('st', 'Sesotho'),
('tn', 'Setswana'),
('sn', 'Shona'),
('ii', 'Sichuan Yi'),
('sd', 'Sindhi'),
('si', 'Sinhalese'),
('ss', 'Siswati'),
('sk', 'Slovak'),
('sl', 'Slovenian'),
('so', 'Somali'),
('nr', 'Southern Ndebele'),
('es', 'Spanish'),
('su', 'Sundanese'),
('sw', 'Swahili (Kiswahili)'),
('ss', 'Swati'),
('sv', 'Swedish'),
('tl', 'Tagalog'),
('ty', 'Tahitian'),
('tg', 'Tajik'),
('ta', 'Tamil'),
('tt', 'Tatar'),
('te', 'Telugu'),
('th', 'Thai'),
('bo', 'Tibetan'),
('ti', 'Tigrinya'),
('to', 'Tonga'),
('ts', 'Tsonga'),
('tr', 'Turkish'),
('tk', 'Turkmen'),
('tw', 'Twi'),
('ug', 'Uyghur'),
('uk', 'Ukrainian'),
('ur', 'Urdu'),
('uz', 'Uzbek'),
('ve', 'Venda'),
('vi', 'Vietnamese'),
('vo', 'Volapük'),
('wa', 'Wallon'),
('cy', 'Welsh'),
('wo', 'Wolof'),
('fy', 'Western Frisian'),
('xh', 'Xhosa'),
('yi', 'Yiddish'),
('ji', 'Yiddish'),
('yo', 'Yoruba'),
('za', 'Zhuang, Chuang'),
('zu', 'Zulu');

--- country_code
insert into book.country_code (code, code_name) VALUES 
('AF', 'Afghanistan'),
('AL', 'Albania'),
('DZ', 'Algeria'),
('AS', 'American Samoa'),
('AD', 'Andorra'),
('AO', 'Angola'),
('AQ', 'Antarctica'),
('AG', 'Antigua And Barbuda'),
('AR', 'Argentina'),
('AM', 'Armenia'),
('AW', 'Aruba'),
('AU', 'Australia'),
('AT', 'Austria'),
('AZ', 'Azerbaijan'),
('BS', 'Bahamas'),
('BH', 'Bahrain'),
('BD', 'Bangladesh'),
('BB', 'Barbados'),
('BY', 'Belarus'),
('BE', 'Belgium'),
('BZ', 'Belize'),
('BJ', 'Benin'),
('BM', 'Bermuda'),
('BT', 'Bhutan'),
('BO', 'Bolivia'),
('BA', 'Bosnia And Herzegovina'),
('BW', 'Botswana'),
('BV', 'Bouvet Island'),
('BR', 'Brazil'),
('IO', 'British Indian Ocean Territory'),
('BN', 'Brunei Darussalam'),
('BG', 'Bulgaria'),
('BF', 'Burkina Faso'),
('BI', 'Burundi'),
('KH', 'Cambodia'),
('CM', 'Cameroon'),
('CA', 'Canada'),
('CV', 'Cape Verde'),
('KY', 'Cayman Islands'),
('CF', 'Central African Republic'),
('TD', 'Chad'),
('CL', 'Chile'),
('CN', 'China'),
('CX', 'Christmas Island'),
('CC', 'Cocos (Keeling) Islands'),
('CO', 'Colombia'),
('KM', 'Comoros'),
('CG', 'Congo'),
('CD', 'Congo, The Democratic Republic Of The'),
('CK', 'Cook Islands'),
('CR', 'Costa Rica'),
('CI', 'Côte D''ivoire'),
('HR', 'Croatia'),
('CU', 'Cuba'),
('CY', 'Cyprus'),
('CZ', 'Czech Republic'),
('DK', 'Denmark'),
('DJ', 'Djibouti'),
('DM', 'Dominica'),
('DO', 'Dominican Republic'),
('EC', 'Ecuador'),
('EG', 'Egypt'),
('SV', 'El Salvador'),
('GQ', 'Equatorial Guinea'),
('ER', 'Eritrea'),
('EE', 'Estonia'),
('ET', 'Ethiopia'),
('FK', 'Falkland Islands (Malvinas)'),
('FO', 'Faroe Islands'),
('FJ', 'Fiji'),
('FI', 'Finland'),
('FR', 'France'),
('GF', 'French Guiana'),
('PF', 'French Polynesia'),
('TF', 'French Southern Territories'),
('GA', 'Gabon'),
('GM', 'Gambia'),
('GE', 'Georgia'),
('DE', 'Germany'),
('GH', 'Ghana'),
('GI', 'Gibraltar'),
('GR', 'Greece'),
('GL', 'Greenland'),
('GD', 'Grenada'),
('GP', 'Guadeloupe'),
('GU', 'Guam'),
('GT', 'Guatemala'),
('GN', 'Guinea'),
('GW', 'Guinea-Bissau'),
('GY', 'Guyana'),
('HT', 'Haiti'),
('HM', 'Heard Island And Mcdonald Islands'),
('HN', 'Honduras'),
('HK', 'Hong Kong'),
('HU', 'Hungary'),
('IS', 'Iceland'),
('IN', 'India'),
('ID', 'Indonesia'),
('IR', 'Iran, Islamic Republic Of'),
('IQ', 'Iraq'),
('IE', 'Ireland'),
('IL', 'Israel'),
('IT', 'Italy'),
('JM', 'Jamaica'),
('JP', 'Japan'),
('JO', 'Jordan'),
('KZ', 'Kazakhstan'),
('KE', 'Kenya'),
('KI', 'Kiribati'),
('KP', 'Korea, Democratic People''s Republic Of'),
('KR', 'Korea, Republic Of'),
('KW', 'Kuwait'),
('KG', 'Kyrgyzstan'),
('LA', 'Lao People''s Democratic Republic'),
('LV', 'Latvia'),
('LB', 'Lebanon'),
('LS', 'Lesotho'),
('LR', 'Liberia'),
('LY', 'Libyan Arab Jamahiriya'),
('LI', 'Liechtenstein'),
('LT', 'Lithuania'),
('LU', 'Luxembourg'),
('MO', 'Macao'),
('MK', 'Macedonia, The Former Yugoslav Republic Of'),
('MG', 'Madagascar'),
('MW', 'Malawi'),
('MY', 'Malaysia'),
('MV', 'Maldives'),
('ML', 'Mali'),
('MT', 'Malta'),
('MH', 'Marshall Islands'),
('MQ', 'Martinique'),
('MR', 'Mauritania'),
('MU', 'Mauritius'),
('YT', 'Mayotte'),
('MX', 'Mexico'),
('FM', 'Micronesia, Federated States Of'),
('MD', 'Moldova, Republic Of'),
('MD', 'Monaco'),
('MN', 'Mongolia'),
('MS', 'Montserrat'),
('MA', 'Morocco'),
('MZ', 'Mozambique'),
('MM', 'Myanmar'),
('NA', 'Namibia'),
('NR', 'Nauru'),
('NP', 'Nepal'),
('NL', 'Netherlands'),
('AN', 'Netherlands Antilles'),
('NC', 'New Caledonia'),
('NZ', 'New Zealand'),
('NI', 'Nicaragua'),
('NE', 'Niger'),
('NG', 'Nigeria'),
('NU', 'Niue'),
('NF', 'Norfolk Island'),
('MP', 'Northern Mariana Islands'),
('NO', 'Norway'),
('OM', 'Oman'),
('PK', 'Pakistan'),
('PW', 'Palau'),
('PS', 'Palestinian Territory, Occupied'),
('PA', 'Panama'),
('PG', 'Papua New Guinea'),
('PY', 'Paraguay'),
('PE', 'Peru'),
('PH', 'Philippines'),
('PN', 'Pitcairn'),
('PL', 'Poland'),
('PR', 'Puerto Rico'),
('QA', 'Qatar'),
('RE', 'Réunion'),
('RO', 'Romania'),
('RU', 'Russian Federation'),
('RW', 'Rwanda'),
('SH', 'Saint Helena'),
('KN', 'Saint Kitts And Nevis'),
('LC', 'Saint Lucia'),
('PM', 'Saint Pierre And Miquelon'),
('VC', 'Saint Vincent And The Grenadines'),
('WS', 'Samoa'),
('SM', 'San Marino'),
('ST', 'Sao Tome And Principe'),
('SA', 'Saudi Arabia'),
('SN', 'Senegal'),
('CS', 'Serbia And Montenegro'),
('SC', 'Seychelles'),
('SL', 'Sierra Leone'),
('SG', 'Singapore'),
('SK', 'Slovakia'),
('SI', 'Slovenia'),
('SB', 'Solomon Islands'),
('SO', 'Somalia'),
('ZA', 'South Africa'),
('GS', 'South Georgia And The South Sandwich Islands'),
('ES', 'Spain'),
('LK', 'Sri Lanka'),
('SD', 'Sudan'),
('SR', 'Suriname'),
('SJ', 'Svalbard And Jan Mayen'),
('SZ', 'Swaziland'),
('SE', 'Sweden'),
('CH', 'Switzerland'),
('SY', 'Syrian Arab Republic'),
('TW', 'Taiwan, Province Of China'),
('TJ', 'Tajikistan'),
('TZ', 'Tanzania, United Republic Of'),
('TH', 'Thailand'),
('TL', 'Timor-Leste'),
('TG', 'Togo'),
('TK', 'Tokelau'),
('TO', 'Tonga'),
('TT', 'Trinidad And Tobago'),
('TN', 'Tunisia'),
('TR', 'Turkey'),
('TM', 'Turkmenistan'),
('TC', 'Turks And Caicos Islands'),
('TV', 'Tuvalu'),
('UG', 'Uganda'),
('UA', 'Ukraine'),
('AE', 'United Arab Emirates'),
('GB', 'United Kingdom'),
('US', 'United States'),
('UM', 'United States Minor Outlying Islands'),
('UY', 'Uruguay'),
('UZ', 'Uzbekistan'),
('VU', 'Vanuatu'),
('VE', 'Venezuela'),
('VN', 'Viet Nam'),
('VG', 'Virgin Islands, British'),
('VI', 'Virgin Islands, U.S.'),
('WF', 'Wallis And Futuna'),
('EH', 'Western Sahara'),
('YE', 'Yemen'),
('ZM', 'Zambia'),
('ZW', 'Zimbabwe');


--- media
INSERT INTO book.media (media_name) VALUES
('könyv'),
('könyv - puha borító'),
('könyv - kemény borító'),
('könyv - hasonmás'),
('füzet'),
('Hangos könyv'),
('CD'),
('DVD'),
('vinyl');

--- author_type
INSERT INTO book.author_type (author_type_name) values
('szerző'),
('társszerző'),
('illusztrátor'),
('fordító'),
('lektor');

--- store
INSERT INTO book.store (store_name) values
('nappali'),
('étkező'),
('kis szoba'),
('háló'),
('bérelt raktár');

--- store
INSERT INTO book.book_storage (store_id, storage_name) VALUES
( (SELECT id from book.store where description = 'nappali'), 'alacsony fa polc /1' ),
( (SELECT id from book.store where description = 'nappali'), 'alacsony fa polc /2' ),
( (SELECT id from book.store where description = 'nappali'), 'alacsony fa polc /3' ),
( (SELECT id from book.store where description = 'nappali'), 'alacsony fa polc /4' ),
( (SELECT id from book.store where description = 'nappali'), 'alacsony fa polc /5' ),
( (SELECT id from book.store where description = 'nappali'), 'magas keskeny /1' ),
( (SELECT id from book.store where description = 'nappali'), 'magas keskeny /2' ),
( (SELECT id from book.store where description = 'nappali'), 'magas keskeny /3' ),
( (SELECT id from book.store where description = 'nappali'), 'magas keskeny /4' ),
( (SELECT id from book.store where description = 'nappali'), 'magas keskeny /5' ),
( (SELECT id from book.store where description = 'nappali'), 'magas keskeny /6' ),
( (SELECT id from book.store where description = 'nappali'), 'magas keskeny /7' ),
( (SELECT id from book.store where description = 'háló'), 'magas széles /1' ),
( (SELECT id from book.store where description = 'háló'), 'magas széles /2' ),
( (SELECT id from book.store where description = 'háló'), 'magas széles /3' ),
( (SELECT id from book.store where description = 'háló'), 'magas széles /4' ),
( (SELECT id from book.store where description = 'háló'), 'magas széles /5' ),
( (SELECT id from book.store where description = 'háló'), 'magas széles /6' ),
( (SELECT id from book.store where description = 'háló'), 'magas széles /7' ),
( (SELECT id from book.store where description = 'nappali'), 'peremes /1' ),
( (SELECT id from book.store where description = 'nappali'), 'peremes /2' ),
( (SELECT id from book.store where description = 'nappali'), 'peremes /3' ),
( (SELECT id from book.store where description = 'nappali'), 'peremes /4' ),
( (SELECT id from book.store where description = 'nappali'), 'peremes /5' ),
( (SELECT id from book.store where description = 'nappali'), 'peremes /6' ),
( (SELECT id from book.store where description = 'nappali'), 'peremes /7' ),
( (SELECT id from book.store where description = 'nappali'), 'könyvfal A/0' ),
( (SELECT id from book.store where description = 'nappali'), 'könyvfal A/1' ),
( (SELECT id from book.store where description = 'nappali'), 'könyvfal A/2' ),
( (SELECT id from book.store where description = 'nappali'), 'könyvfal A/3' ),
( (SELECT id from book.store where description = 'nappali'), 'könyvfal A/4' ),
( (SELECT id from book.store where description = 'nappali'), 'könyvfal A/5' ),
( (SELECT id from book.store where description = 'nappali'), 'könyvfal A/6' ),
( (SELECT id from book.store where description = 'nappali'), 'könyvfal B/0' ),
( (SELECT id from book.store where description = 'nappali'), 'könyvfal B/1' ),
( (SELECT id from book.store where description = 'nappali'), 'könyvfal B/2' ),
( (SELECT id from book.store where description = 'nappali'), 'könyvfal B/3' ),
( (SELECT id from book.store where description = 'nappali'), 'könyvfal B/4' ),
( (SELECT id from book.store where description = 'nappali'), 'könyvfal B/5' ),
( (SELECT id from book.store where description = 'nappali'), 'könyvfal B/6' ),
( (SELECT id from book.store where description = 'nappali'), 'könyvfal C/0' ),
( (SELECT id from book.store where description = 'nappali'), 'könyvfal C/1' ),
( (SELECT id from book.store where description = 'nappali'), 'könyvfal C/2' ),
( (SELECT id from book.store where description = 'nappali'), 'könyvfal C/3' ),
( (SELECT id from book.store where description = 'nappali'), 'könyvfal C/4' ),
( (SELECT id from book.store where description = 'nappali'), 'könyvfal C/5' ),
( (SELECT id from book.store where description = 'nappali'), 'könyvfal C/6' ),
( (SELECT id from book.store where description = 'nappali'), 'könyvfal D/0' ),
( (SELECT id from book.store where description = 'nappali'), 'könyvfal D/1' ),
( (SELECT id from book.store where description = 'nappali'), 'könyvfal D/2' ),
( (SELECT id from book.store where description = 'nappali'), 'könyvfal D/3' ),
( (SELECT id from book.store where description = 'nappali'), 'könyvfal D/4' ),
( (SELECT id from book.store where description = 'nappali'), 'könyvfal D/5' ),
( (SELECT id from book.store where description = 'nappali'), 'könyvfal D/6' ),
( (SELECT id from book.store where description = 'nappali'), 'könyvfal E/0' ),
( (SELECT id from book.store where description = 'nappali'), 'könyvfal E/1' ),
( (SELECT id from book.store where description = 'nappali'), 'könyvfal E/2' ),
( (SELECT id from book.store where description = 'nappali'), 'könyvfal E/3' ),
( (SELECT id from book.store where description = 'nappali'), 'könyvfal E/4' ),
( (SELECT id from book.store where description = 'nappali'), 'könyvfal E/5' ),
( (SELECT id from book.store where description = 'nappali'), 'könyvfal E/6' );


--- title_type
INSERT INTO book.title_type (type_name) values
('főcím'),
('alcím'),
('módosítás'),
('eredeti');


INSERT INTO book.genre (genre_name) values
('Romantikus'),
('Erotikus'),
('Fantasy'),
('Disztópia'),
('Ifjúsági könyvek'),
('Történelmi könyvek'),
('Történelmi romantikus'),
('Mese'),
('Krimi'),
('Sci-Fi'), 
('Szépirodalom'),
('eposz'),
('regény'),
('novella'),
('mese'),
('monda'),
('mítosz'),
('elbeszélő költemény'),
('vers'),
('dal'),
('óda'),
('elégia'),
('epigramma'),
('himnusz'),
('rapszódia'),
('tragédia'),
('vígjáték'),
('tragikomédia'),
('középfajú dráma');


INSERT INTO book.doc_series (description) values
('Kingsbridge sorozat'),
('Hunyadi sorozat');


INSERT INTO book.publisher (publisher_name) VALUES
('Európa Könyvkiadó Budapest'),
('Akadémiai Kiadó Budapest'),
('Babits Kiadó Szekszárd'),
('Gold Book Kiadó'),
('GABO Könyvkiadó'),
('Agave Könyvek'),
('Mikes Kiadó');

INSERT INTO book.issue_series (isbn, publisher_id, description) values
('963-8318-13-9', (SELECT id from book.publisher where publisher_name = 'Babits Kiadó Szekszárd'), 'Mikszáth Kálmán művei'),
('963-8318-13-9', (SELECT id from book.publisher where publisher_name = 'Európa Könyvkiadó Budapest'), 'A Világirodalom Remekei'),
('963-8318-13-9', (SELECT id from book.publisher where publisher_name = 'Akadémiai Kiadó Budapest'), 'Jókai Összes Művei');


insert INTO book.person (prefix, nickname, forename, middle_name, surname, suffix, born, died, nationality_id, language_id, person_url) values
(null, null,'Henryk', 'Adam Aleksander Pius', 'Sienkiewicz', null, '1846-05-05'::date, '1916-11-15'::date, (SELECT id from book.country_code where code = 'PL'), (SELECT id from book.language_code where code = 'pl'), 'https://hu.wikipedia.org/wiki/Henryk_Sienkiewicz'),
(null, null, 'István', null, 'Mészáros', null, null, null, (SELECT id from book.country_code where code = 'HU'), (SELECT id from book.language_code where code = 'hu'), null),
(null, 'Stendhal','Marie-Henri', null, 'Beylez', null, '1783-01-23'::date, '1842-03-23'::date, (SELECT id from book.country_code where code = 'FR'), (SELECT id from book.language_code where code = 'fr'), 'https://hu.wikipedia.org/wiki/Stendhal'),
(null, null,'Endre', null, 'Illés', null, null, null, (SELECT id from book.country_code where code = 'HU'), (SELECT id from book.language_code where code = 'hu'), null),
(null, null,'Egon', 'Erwin', 'Kirsch', null, '1885-04-29'::date, '1946-03-31'::date, (SELECT id from book.country_code where code = 'CZ'), (SELECT id from book.language_code where code = 'cs'), 'https://hu.wikipedia.org/wiki/Egon_Erwin_Kisch'),
(null, null,'Éva', null, 'Gordon', null, null, null, (SELECT id from book.country_code where code = 'HU'), (SELECT id from book.language_code where code = 'hu'), null),
(null, null,'Nikosz', null, 'Kazantzakisz', null, '1883-02-18'::date, '1957-10-26'::date, (SELECT id from book.country_code where code = 'GR'), (SELECT id from book.language_code where code = 'el'), 'https://hu.wikipedia.org/wiki/N%C3%ADkosz_Kazandz%C3%A1kisz'),
(null, null,'Árpád', null, 'Papp', null, null, null, (SELECT id from book.country_code where code = 'HU'), (SELECT id from book.language_code where code = 'hu'), null),
(null, null,'Kálmán', null, 'Szabó', null, null, null, (SELECT id from book.country_code where code = 'HU'), (SELECT id from book.language_code where code = 'hu'), null),
(null, null,'Dimitriosz', null, 'Hadzsisz', null, null, null, (SELECT id from book.country_code where code = 'HU'), (SELECT id from book.language_code where code = 'hu'), null),
(null, 'Ernst Theodor Amadeus Hoffmann','Ernst', 'Theodor', 'Wilhelm', null, '1776-01-24'::date, '1822-06-25'::date, (SELECT id from book.country_code where code = 'DE'), (SELECT id from book.language_code where code = 'de'), 'https://hu.wikipedia.org/wiki/E._T._A._Hoffmann'),
(null, null,'Erzsébet', null, 'Gergely', null, null, null, (SELECT id from book.country_code where code = 'HU'), (SELECT id from book.language_code where code = 'hu'), null),
(null, null, 'Heinrich', 'von', 'Kleist', null, '1777-10-18'::date, '1811-11-21'::date, (SELECT id from book.country_code where code = 'DE'), (SELECT id from book.language_code where code = 'de'), 'https://hu.wikipedia.org/wiki/Heinrich_von_Kleist'),
(null, null,'László', null, 'Kardos', null, null, null, (SELECT id from book.country_code where code = 'HU'), (SELECT id from book.language_code where code = 'hu'), null),
(null, null, 'Adelbert', 'von', 'Chamisso', null, '1781-01-30'::date, '1838-08-21'::date, (SELECT id from book.country_code where code = 'FR'), (SELECT id from book.language_code where code = 'de'), 'https://hu.wikipedia.org/wiki/Adelbert_von_Chamisso'),
(null, null,'Lajos', null, 'Bálint', null, null, null, (SELECT id from book.country_code where code = 'HU'), (SELECT id from book.language_code where code = 'hu'), null),
(null, null, 'Joseph', 'von', 'Eichendorff', null, '1788-03-10'::date, '1857-11-26'::date, (SELECT id from book.country_code where code = 'DE'), (SELECT id from book.language_code where code = 'de'), 'https://hu.wikipedia.org/wiki/Joseph_von_Eichendorff'),
(null, null,'Miklós', null, 'Vajda', null, null, null, (SELECT id from book.country_code where code = 'HU'), (SELECT id from book.language_code where code = 'hu'), null),
(null, null, 'Eduard', null, 'Mörike', null, '1804-09-08'::date, '1875-06-04'::date, (SELECT id from book.country_code where code = 'DE'), (SELECT id from book.language_code where code = 'de'), 'https://hu.wikipedia.org/wiki/Eduard_M%C3%B6rike'),
(null, null,'Balázs', null, 'Lengyel', null, null, null, (SELECT id from book.country_code where code = 'HU'), (SELECT id from book.language_code where code = 'hu'), null),
(null, 'Theodor Storm', 'Hans', 'Theodor Woldsen', 'Storm', null, '1817-09-14'::date, '1888-06-04'::date, (SELECT id from book.country_code where code = 'DE'), (SELECT id from book.language_code where code = 'de'), 'https://hu.wikipedia.org/wiki/Theodor_Storm'),
(null, null,'Ede', null, 'Szabó', null, null, null, (SELECT id from book.country_code where code = 'HU'), (SELECT id from book.language_code where code = 'hu'), null),
(null, null, 'Gottfried', null, 'Keller', null, '1819-07-19'::date, '1890-07-15'::date, (SELECT id from book.country_code where code = 'CH'), (SELECT id from book.language_code where code = 'de'), 'https://hu.wikipedia.org/wiki/Gottfried_Keller'),
(null, null,'Ede', null, 'Szabó', null, null, null, (SELECT id from book.country_code where code = 'HU'), (SELECT id from book.language_code where code = 'hu'), null),
(null, null, 'Ilja', 'Grigorjevics', 'Ehrenburg', null, '1891-01-14'::date, '1967-08-30'::date, (SELECT id from book.country_code where code = 'UA'), (SELECT id from book.language_code where code = 'ru'), 'https://hu.wikipedia.org/wiki/Ilja_Grigorjevics_Ehrenburg'),
(null, null,'Sándor', null, 'Benamy', null, null, null, (SELECT id from book.country_code where code = 'HU'), (SELECT id from book.language_code where code = 'hu'), null),
(null, null, 'Roger', 'Martin', 'du Gard', null, '1881-03-22'::date, '1958-08-22'::date, (SELECT id from book.country_code where code = 'FR'), (SELECT id from book.language_code where code = 'fr'), 'https://hu.wikipedia.org/wiki/Roger_Martin_du_Gard'),
(null, null,'Marcell', null, 'Benedek', null, null, null, (SELECT id from book.country_code where code = 'HU'), (SELECT id from book.language_code where code = 'hu'), null),
(null, 'Richard Hughes', 'Richard', 'Arthur Warren', 'Hughes', null, '1900-04-19'::date, '1976-04-28'::date, (SELECT id from book.country_code where code = 'GB'), (SELECT id from book.language_code where code = 'en'), 'https://en.wikipedia.org/wiki/Richard_Hughes_(British_writer)'),
(null, null,'Péter', null, 'Balabán', null, null, null, (SELECT id from book.country_code where code = 'HU'), (SELECT id from book.language_code where code = 'hu'), null),
(null, null,'Iván', null, 'Boldizsár', null, null, null, (SELECT id from book.country_code where code = 'HU'), (SELECT id from book.language_code where code = 'hu'), null),
(null, null,'Albert', null, 'Gyergyai', null, null, null, (SELECT id from book.country_code where code = 'HU'), (SELECT id from book.language_code where code = 'hu'), null),
(null, null, 'Romain', null, 'Rolland', null, '1866-01-29'::date, '1944-12-30'::date, (SELECT id from book.country_code where code = 'FR'), (SELECT id from book.language_code where code = 'fr'), 'https://hu.wikipedia.org/wiki/Romain_Rolland'),
(null, null,'György', null, 'Rónai', null, null, null, (SELECT id from book.country_code where code = 'HU'), (SELECT id from book.language_code where code = 'hu'), null),
(null, null, 'André', null, 'Gide', null, '1869-11-22'::date, '1951-02-19'::date, (SELECT id from book.country_code where code = 'FR'), (SELECT id from book.language_code where code = 'fr'), 'https://hu.wikipedia.org/wiki/Andr%C3%A9_Gide'),
(null, null, 'Valery', null, 'Larbaud', null, '1881-08-29'::date, '1957-02-02'::date, (SELECT id from book.country_code where code = 'FR'), (SELECT id from book.language_code where code = 'fr'), 'https://hu.wikipedia.org/wiki/Valery_Larbaud'),
(null, null,'Nándor', null, 'Szávai', null, null, null, (SELECT id from book.country_code where code = 'HU'), (SELECT id from book.language_code where code = 'hu'), null),
(null, null, 'François', null, 'Mauriac', null, '1885-10-11'::date, '1970-09-01'::date, (SELECT id from book.country_code where code = 'FR'), (SELECT id from book.language_code where code = 'fr'), 'https://hu.wikipedia.org/wiki/Fran%C3%A7ois_Mauriac'),
(null, null,'Judit', null, 'Pór', null, null, null, (SELECT id from book.country_code where code = 'HU'), (SELECT id from book.language_code where code = 'hu'), null),
(null, null, 'Raymond', null, 'Radiguet', null, '1903-06-18'::date, '1923-12-12'::date, (SELECT id from book.country_code where code = 'FR'), (SELECT id from book.language_code where code = 'fr'), 'https://en.wikipedia.org/wiki/Raymond_Radiguet'),
(null, null,'Miklós', null, 'Zigány', null, null, null, (SELECT id from book.country_code where code = 'HU'), (SELECT id from book.language_code where code = 'hu'), null),
(null, 'Jean-Paul Sartre', 'Jean-Paul', 'Charles Aymard', 'Sartre', null, '1905-04-21'::date, '1980-04-15'::date, (SELECT id from book.country_code where code = 'FR'), (SELECT id from book.language_code where code = 'fr'), 'https://en.wikipedia.org/wiki/Jean-Paul_Sartre'),
(null, null,'Pál', null, 'Justus', null, null, null, (SELECT id from book.country_code where code = 'HU'), (SELECT id from book.language_code where code = 'hu'), null),
(null, 'Bertolt Brecht', 'Eugen', 'Berthold Friedrich Brecht', 'Sartre', null, '1898-02-10'::date, '1956-08-14'::date, (SELECT id from book.country_code where code = 'DE'), (SELECT id from book.language_code where code = 'de'), 'https://en.wikipedia.org/wiki/Bertolt_Brecht'),
(null, null,'Árpád', null, 'Fáy', null, null, null, (SELECT id from book.country_code where code = 'HU'), (SELECT id from book.language_code where code = 'hu'), null),
(null, null, 'Alekszej', 'Nyikolajevics', 'Tolsztoj', null, '1883-01-10'::date, '1945-02-23'::date, (SELECT id from book.country_code where code = 'RU'), (SELECT id from book.language_code where code = 'ru'), 'https://hu.wikipedia.org/wiki/Alekszej_Nyikolajevics_Tolsztoj'),
(null, null,'László', null, 'Németh', null, null, null, (SELECT id from book.country_code where code = 'HU'), (SELECT id from book.language_code where code = 'hu'), null);
